### ISSUE TITLE
Add sentry.io for error monitoring

### ISSUE THREAD

**Issue by davidharting** [davidharting/nails#7]
# Tasks
- [ ] Add source maps to next build
- [ ] Evaluate Heroku plugin for Sentry
- [ ] Implement integration
- [ ] Validate working for backend
- [ ] Validate working for frontend
- [ ] Determine how to handle environments
  - [ ] Local dev
  - [ ] Production
  - [ ] Automated testing
